bases:
- cainjector
- cert-manager-controller
- webhook

commonLabels:
  app.kubernetes.io/version: 0.10.1
  app.kubernetes.io/component: cert-manager
  app.kubernetes.io/part-of: fury-kubernetes-ingress
  app.kubernetes.io/managed-by: kustomize
